filebeat.inputs:
  # - type: filestream
    # id: logs
    # enabled: true
    # paths:
      # - /var/lib/docker/containers/*/*.log
    # parsers:
      # - container: ~
    # tags: ["logs"]

  - type: filestream
    id: json-files
    enabled: true
    paths:
      - /usr/share/filebeat/ingest_data/*.ndjson
    close_inactive: 2m
    tags: ["json-files"]
    parsers:
      - ndjson:
          keys_under_root: true

  - type: filestream
    id: scraper-logs
    enabled: true
    paths:
      - /usr/share/filebeat/ingest_data/scraper*.log
    parsers:
    tags: ["scraper"]

  - type: filestream
    id: chatbot-logs
    enabled: true
    paths:
      - /usr/share/filebeat/ingest_data/chatbot*.log
    parsers:
    tags: ["chatbot"]


output.logstash:
  hosts: ["${LOGSTASH_HOSTS}"]