version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - /elk-share/registry:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager        
          - node.hostname == proyecto-vm1
    networks:
      - registry-net

networks:
  registry-net:
    driver: overlay
    attachable: true
